$(function(){
    $("#insertForm").validate({
        debug:true,
        submitHandler:function(form){
            form.submit();
        },
        rules:{
            mid:{
                required:true
            }
        }
    })
});